### ISSUE TITLE
Timber Wolf TBR-D SSRM6 does not fire

### ISSUE THREAD

**Issue by kwadroke** [harbdog/pixelmek-3d#23]
When using the Timber Wolf TBR-D, PPCs fire fine, but the SSRM6 does not. There is no graphics, sound, nor damage when firing the SSRM6 weapons.

Using latest commit as of this post: 7bfd0e6

I'm sure this is still a Work In Progress, but figured I'd let you know.
Great Project so far!

**Comment by harbdog** [comment]
Hey there

**Comment by kwadroke** [comment]
hmmm... thought I did have a lock. Will test again.

**Comment by kwadroke** [comment]
Yep. I apparently didn't have lock previously. Sorry about that.

**Comment by harbdog** [comment]
> hmmm... thought I did have a lock. Will test again.
> 

The problem is that you lose lock too easily when not precisely on the target. I'll probably need to have something that can keep the lock at 100% for some period of time after reticle leaves target before it starts to diminish.

**Comment by kwadroke** [comment]
> Hey there, didn't know anyone was paying attention here haha!

Been following and playing for a while now.

**Comment by kwadroke** [comment]
> The problem is that you lose lock too easily when not precisely on the target. I'll probably need to have something that can keep the lock at 100% for some period of time after reticle leaves target before it starts to diminish.

Usually I stand pretty close when testing, but may have been too far away or targeting the moving mechs.

**Comment by harbdog** [comment]
@kwadroke good news, just added sound effects for cycling weapons, setting weapon groups, and for streak SRM that do not have target lock :)

https://github.com/harbdog/pixelmek-3d/commit/c6481c1bb1be4304f1cdb2dae58a839ed2c1e90a

**Comment by kwadroke** [comment]
Cool.
